language: node_js
node_js:
- node
before_install:
- "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
- npm install -g greenkeeper-lockfile@1
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: oscblgm@gmail.com
  api_key:
    secure: atpmSmbAzyqGMXr06uK5Z7teJQb92DzIR0q+4UD9i0x0d4ss72m4EsJnziDNyY9GMFwXy1ftv/vsqTm7as80xV+sdwq1R2FEp2qdzkTB9xo/+wx4ccB6l1lf7mheJKwaU6wl9+DnHgZhfrsVMyO9b91cCS0bq2JJavqb08qjBuV1/dQsEL57ZcM53aR3vDN+KIAkTmNSznnyK+fdUEnM/p1kx1Flq93qdzigRz7d/BDDSCADjRtirgJbBvSSFwPy9bYtvPwKp5LU1VT+2jbLQEKQ0xkrZtHJ54IqTJ5odZwx1eiU6zx0yJQnhg07YkiOuFALJu43x8G0aCTokglAIgMPOy+Ur8mBBoPpdI31dm3eDzD8R9JOgzWTss2mYzQQ+HElp54PxlW7GmqWdAmGcY1CWWm2JOnQwfdsqWHLxelmPhCciiZrVebdsYYLBPwRwnwKav6FLMMLXijpjyk5UrMkk7NvH7GOUP0gvbHviyKwx59rQgOQuKrJa9r9OCN04NF2s7KzRWfm3EvBpe4SG0+qE0etFCnJ2O0JBF331BsMGOuUZaIq/CwsoBmtJWxnD6Ntt8iGz2ozbTQRcgBPwnI/JnVsfBXo869BSQrwgRSrfIDmWOs5S80gClFLbGvCnabijit4hivqC/V8KvaZ5vxDFpyxnWCwT3BYiSOueEs=
  on:
    repo: blgm/redux-bind-selectors
